### ISSUE TITLE
Is there a better way?

### ISSUE THREAD

**Issue by user-mobil** [kudoleh/iOS-Clean-Architecture-MVVM#8]
https://github.com/kudoleh/iOS-Clean-Architecture-MVVM/blob/a5afd66e5910db61815af7f84369f06a1fd808bb/ExampleMVVM/Data/PersistentStorages/CoreDataStorage/CoreDataStorage.swift#L25

Hi. I really appreciate your repository. I was wondering what you believe the best way to solve or propagate errors in this clean architecture would be, for a shipping application.

**Comment by kudoleh** [comment]
Hi, Thank you! Great question!

How to handle error depends on how critical error and what kind or error is. In this case I would log this error in Firebase Crashlytics because I use persistence only for persisting(caching) response and recent queries which is not critical functionally, and app can continue working and providing the key functionality, logging this error will be enough and then inspecting it in Firebase and fixing it.

Then examples of error handling and propagations you can find here:

- [example on Networking Layer](https://github.com/kudoleh/iOS-Clean-Architecture-MVVM/blob/201de7759e2d5634e3bb4b5ad524c4242c62b306/ExampleMVVM/Infrastructure/Network/NetworkService.swift#L84)

- [here on Persistence Level](https://github.com/kudoleh/iOS-Clean-Architecture-MVVM/blob/201de7759e2d5634e3bb4b5ad524c4242c62b306/ExampleMVVM/Data/PersistentStorages/MoviesResponseStorage/CoreDataMoviesResponseStorage.swift#L50) 

- Also good example of Internet No Connection Error handling [here](https://github.com/kudoleh/iOS-Clean-Architecture-MVVM/blob/201de7759e2d5634e3bb4b5ad524c4242c62b306/ExampleMVVM/Presentation/MoviesScene/MoviesList/ViewModel/MoviesListViewModel.swift#L116): 

```
    private func handle(error: Error) {
        self.error.value = error.isInternetConnectionError ?
            NSLocalizedString("No internet connection", comment: "") :
            NSLocalizedString("Failed loading movies", comment: "")
    }
```


How to handle an error and on what level depends on the kind of error.

For all our errors we show to users only more generic errors like: "Something went wrong, we are working on fixing it" or connection error. And internally we handle them and log them in Crashlytics.

Also these Examples show that use of **Result, Result.MapError** and **throw** are used to propagate and handle errors.

**Comment by user-mobil** [comment]
Thank you!! Very much appreciated.
